# Ansible plabook for threetier using roles

# ansible-galaxy init nginx_role
# ansible-galaxy init php_role
# ansible-galaxy init db_role

# cd nginx_role/tasks/ && nano main.yml
# tasks file for nginx_role
- name: install nginx
  apt:
   name: nginx
   state: present
- name: start nginx
  service:
   name: nginx
   state: started

# cd php_role/tasks/ && nano main.yml
# tasks file for php_role
- name: update apt
  apt:
   name: '*'
   state: latest
- name: install php
  apt:
   name: php
   state: present
- name: install php-fpm
  apt:
   name: php8.3-fpm
   state: present
- name: start php-fpm
  service:
   name: php8.3-fpm
   state: started

# cd db_role/tasks/ && nano main.yml
# tasks file for db_role
- name: install mysql
  apt:
   name: mariadb-server
   state: present
- name: start mysql
  service:
   name: mariadb
   state: started
  notify: restart nginx
  notify: restart php-fpm
  notify: restart mysql

# cd db_role/handlers/ && nano main.yml  
# handlers file for db_role
- name: restart nginx
  service: name=nginx state=restarted
- name: restart php-fpm
  service: name=php8.3-fpm state=restarted
- name: restart mysql
  service: name=mariadb state=restarted 
  
# cd to ansible working directory and create main.yml 
- name: threetier using roles
  hosts: localhost
  become: true
  connection: local
  roles:
   - { role: nginx_role }
   - { role: php_role }
   - { role: db_role }

# Run playbook: ansible-playbook main.yml  
  

   
