## Ansible Playbook for Three-Tier Architecture Deployment
## define inventory—the list of managed hosts
[webserver]
172.31.9.40 ansible_ssh_user=ubuntu ansible_private_key_file=FirstServer.pem
[appserver]
172.31.5.99 ansible_ssh_user=ubuntu ansible_private_key_file=FirstServer.pem
[dbserver]
172.31.6.81 ansible_ssh_user=ubuntu ansible_private_key_file=FirstServer.pem

- name: myplay1
  hosts: all
  become: true
  tasks:
   - name: install nginx
     apt:
      name: nginx
      state: present
     when: inventory_hostname in groups['webserver']
   - name: start nginx service
     service:
      name: nginx
      state: started
     when: inventory_hostname in groups['webserver']
   - name: install php
     apt:
      name: php
      state: present
     when: inventory_hostname in groups['appserver']
   - name: update apt
     shell: 'apt update'
   - name: install php8.3-fpm
     apt:
      name: php8.3-fpm
      state: present
     when: inventory_hostname in groups['appserver']
   - name: start php-fpm service
     service:
      name: php8.3-fpm
      state: started
     when: inventory_hostname in groups['appserver']
   - name: install mysql
     apt:
      name: mariadb-server
      state: present
     when: inventory_hostname in groups['dbserver']
   - name: start mysql service
     service:
      name: mariadb
      state: started
     when: inventory_hostname in groups['dbserver']
